# This is for production
services:
  backend:
    image: flask-api
    build:
      context: ./server
      target: production
    ports:
      - "5001:5001"
    command: python run.py

  frontend:
    build:
      context: ./client
      target: production
    ports:
      - "3000:3000"
    command: npm run start
