# This is for development
services:
  backend-dev:
    image: flask-api-dev
    build:
      context: ./server
      target: base
    ports:
      - "5001:5001"
    volumes: # Mount the volumes
      - ./server:/app
    command: python run.py

  frontend:
    image: nextjs-app-dev
    build:
      context: ./client
      target: base
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    command: ./run.sh
  
  stripe-cli:
    image: stripe/stripe-cli
    container_name: stripe-cli
    command: listen --api-key ${STRIPE_API_KEY} --device-name ${STRIPE_DEVICE_NAME} --forward-to http://backend-dev:5001/api/stripe/webhook
    env_file:
      - .env