export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

import './global.css';

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>Forza</title>
      </head>
      <body>
        {children}
      </body>
    </html>
  )
}
